
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-05
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-05
pull_requests: [{"author":{"id":"U_kgDOCM7mwQ","is_bot":false,"login":"jasminetan0510","name":""},"headRefName":"jt-fix-footer-link","number":27,"title":"jt - updated footer with test","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/27"},{"author":{"id":"U_kgDOCM7mwQ","is_bot":false,"login":"jasminetan0510","name":""},"headRefName":"jt-replace-brand-with-UCSB-dining","number":26,"title":"jt - changed nav bar brand and document title to UCSB Dining","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/26"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-add-moderator-menu","number":25,"title":"MF - Make Moderator a Menu with item 'Moderate Reviews'","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/25"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-Reintroduce-React-Eslint-Rules","number":24,"title":"HY-Add React ESLint plugin with flat config support","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/24"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-remove-placeholder","number":23,"title":"MF - Removed the Placeholder functionalities from AppNavBar and Codebase","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/23"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-bug/no-meals-bad-ux","number":21,"title":"HY-BUG: Bad UX on days where UCSB Dining isn't serving meals","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/21"}]
