
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-05
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-05
pull_requests: [{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-add-moderator-alias-menu","number":50,"title":"MF - Add Moderator Alias Menu","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/50"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-AddWorkingLoadScreens","number":49,"title":"MF- BUG FIX: Implement Loading Screens to Meal Time and Menu Item pages to solve brief \"No meals offered today\" screen","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/49"},{"author":{"id":"MDQ6VXNlcjg4MTE4MjQy","is_bot":false,"login":"amelvinmathew","name":""},"headRefName":"mm-Date-Selector-for-Dinings-Commons-Page","number":44,"title":"mm - added date selector for MenuItemPage","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/44"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-MealsTodayColumn","number":35,"title":"BS - FEATURE: Show meals on page where you can select a dining commons","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/35"}]
