
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-05
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-05
pull_requests: [{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-refactor-issue","number":22,"title":"MF - Refactored the relative import paths to absolute import paths in proj-dining.","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/22"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-bug/no-meals-bad-ux","number":21,"title":"HY-BUG: Bad UX on days where UCSB Dining isn't serving meals","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/21"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"BS-multipleH2","number":20,"title":"BS - Allow Multiple H2 connections","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-05/pull/20"}]
